name: Do stuff

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Perform the thing
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: octo-sts/action@v1.0.0
        id: octo-sts
        with: 
          scope: navikt/jk-tullerepo-1
          identity: jk-tullerepo-2
      - run: |
          git config --global user.email "whatever@users.noreply.github.com"
          git config --global user.name "unimportant"
          git clone https://github.com/navikt/jk-tullerepo-1
          cd jk-tullerepo-1
          gh issue create --title "I found a bug" --body "Nothing works"
        env:
          GITHUB_TOKEN: ${{ steps.octo-sts.outputs.token }}
          GITHUB_ACTOR: ${{ env.GITHUB_ACTOR }}
