name: Do stuff

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Perform the thing
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: octo-sts/action@v1.0.0
        id: octo-sts
        with: 
          scope: navikt/jk-tullerepo-1
          identity: jk-tullerepo-2
      - run: |
          git config --global user.email "$ACTOR@users.noreply.github.com"
          git config --global user.name "$ACTOR"
          git clone https://github.com/navikt/jk-tullerepo-1
          cd jk-tullerepo-1
          echo "app-2 was here @ $(date)" >thefile
          git add thefile 
          git commit -m "did a thing"
          git push "https://$COMMIT_AUTHOR:$GITHUB_TOKEN@github.com/navikt/jk-tullerepo-1"
        env:
          GITHUB_TOKEN: ${{ steps.octo-sts.outputs.token }}
          ACTOR: ${{ env.GITHUB_ACTOR }}
